package app.taolin.cnbeta.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE".
*/
public class ArticleDao extends AbstractDao<Article, String> {

    public static final String TABLENAME = "ARTICLE";

    /**
     * Properties of entity Article.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Sid = new Property(0, String.class, "sid", true, "SID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Time = new Property(2, String.class, "time", false, "TIME");
        public final static Property Source = new Property(3, String.class, "source", false, "SOURCE");
        public final static Property Counter = new Property(4, String.class, "counter", false, "COUNTER");
        public final static Property Good = new Property(5, String.class, "good", false, "GOOD");
        public final static Property Comments = new Property(6, String.class, "comments", false, "COMMENTS");
        public final static Property Hometext = new Property(7, String.class, "hometext", false, "HOMETEXT");
        public final static Property Bodytext = new Property(8, String.class, "bodytext", false, "BODYTEXT");
    };


    public ArticleDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE\" (" + //
                "\"SID\" TEXT PRIMARY KEY NOT NULL ," + // 0: sid
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"TIME\" TEXT NOT NULL ," + // 2: time
                "\"SOURCE\" TEXT NOT NULL ," + // 3: source
                "\"COUNTER\" TEXT NOT NULL ," + // 4: counter
                "\"GOOD\" TEXT NOT NULL ," + // 5: good
                "\"COMMENTS\" TEXT NOT NULL ," + // 6: comments
                "\"HOMETEXT\" TEXT NOT NULL ," + // 7: hometext
                "\"BODYTEXT\" TEXT NOT NULL );"); // 8: bodytext
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Article entity) {
        stmt.clearBindings();
 
        String sid = entity.getSid();
        if (sid != null) {
            stmt.bindString(1, sid);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getTime());
        stmt.bindString(4, entity.getSource());
        stmt.bindString(5, entity.getCounter());
        stmt.bindString(6, entity.getGood());
        stmt.bindString(7, entity.getComments());
        stmt.bindString(8, entity.getHometext());
        stmt.bindString(9, entity.getBodytext());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Article entity) {
        stmt.clearBindings();
 
        String sid = entity.getSid();
        if (sid != null) {
            stmt.bindString(1, sid);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getTime());
        stmt.bindString(4, entity.getSource());
        stmt.bindString(5, entity.getCounter());
        stmt.bindString(6, entity.getGood());
        stmt.bindString(7, entity.getComments());
        stmt.bindString(8, entity.getHometext());
        stmt.bindString(9, entity.getBodytext());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Article readEntity(Cursor cursor, int offset) {
        Article entity = new Article( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // sid
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2), // time
            cursor.getString(offset + 3), // source
            cursor.getString(offset + 4), // counter
            cursor.getString(offset + 5), // good
            cursor.getString(offset + 6), // comments
            cursor.getString(offset + 7), // hometext
            cursor.getString(offset + 8) // bodytext
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Article entity, int offset) {
        entity.setSid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setTime(cursor.getString(offset + 2));
        entity.setSource(cursor.getString(offset + 3));
        entity.setCounter(cursor.getString(offset + 4));
        entity.setGood(cursor.getString(offset + 5));
        entity.setComments(cursor.getString(offset + 6));
        entity.setHometext(cursor.getString(offset + 7));
        entity.setBodytext(cursor.getString(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Article entity, long rowId) {
        return entity.getSid();
    }
    
    @Override
    public String getKey(Article entity) {
        if(entity != null) {
            return entity.getSid();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
