package app.taolin.cnbeta.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ARTICLE".
 */
@Entity
public class Article implements Comparable<Article> {

    @Id
    private String sid;

    @NotNull
    private String title;

    @NotNull
    private String time;

    @NotNull
    private String source;

    @NotNull
    private String counter;

    @NotNull
    private String good;

    @NotNull
    private String comments;

    @NotNull
    private String hometext;

    @NotNull
    private String bodytext;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Article() {
    }

    public Article(String sid) {
        this.sid = sid;
    }

    @Generated
    public Article(String sid, String title, String time, String source, String counter, String good, String comments, String hometext, String bodytext) {
        this.sid = sid;
        this.title = title;
        this.time = time;
        this.source = source;
        this.counter = counter;
        this.good = good;
        this.comments = comments;
        this.hometext = hometext;
        this.bodytext = bodytext;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    @NotNull
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(@NotNull String time) {
        this.time = time;
    }

    @NotNull
    public String getSource() {
        return source;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSource(@NotNull String source) {
        this.source = source;
    }

    @NotNull
    public String getCounter() {
        return counter;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCounter(@NotNull String counter) {
        this.counter = counter;
    }

    @NotNull
    public String getGood() {
        return good;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGood(@NotNull String good) {
        this.good = good;
    }

    @NotNull
    public String getComments() {
        return comments;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComments(@NotNull String comments) {
        this.comments = comments;
    }

    @NotNull
    public String getHometext() {
        return hometext;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHometext(@NotNull String hometext) {
        this.hometext = hometext;
    }

    @NotNull
    public String getBodytext() {
        return bodytext;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBodytext(@NotNull String bodytext) {
        this.bodytext = bodytext;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int compareTo(Article another) {
        return another.time.compareTo(time);
    }
    // KEEP METHODS END

}
