package app.taolin.cnbeta.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import app.taolin.cnbeta.dao.FavorArticle;

import app.taolin.cnbeta.dao.FavorArticleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favorArticleDaoConfig;

    private final FavorArticleDao favorArticleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favorArticleDaoConfig = daoConfigMap.get(FavorArticleDao.class).clone();
        favorArticleDaoConfig.initIdentityScope(type);

        favorArticleDao = new FavorArticleDao(favorArticleDaoConfig, this);

        registerDao(FavorArticle.class, favorArticleDao);
    }
    
    public void clear() {
        favorArticleDaoConfig.getIdentityScope().clear();
    }

    public FavorArticleDao getFavorArticleDao() {
        return favorArticleDao;
    }

}
