package app.taolin.cnbeta.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FAVOR_ARTICLE".
 */
@Entity
public class FavorArticle {

    @Id
    private String sid;

    @NotNull
    private String title;

    @NotNull
    private String pubtime;

    @NotNull
    private String collecttime;
    private String source;

    @NotNull
    private String counter;
    private String good;

    @NotNull
    private String comments;
    private String hometext;
    private String bodytext;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public FavorArticle() {
    }

    public FavorArticle(String sid) {
        this.sid = sid;
    }

    @Generated
    public FavorArticle(String sid, String title, String pubtime, String collecttime, String source, String counter, String good, String comments, String hometext, String bodytext) {
        this.sid = sid;
        this.title = title;
        this.pubtime = pubtime;
        this.collecttime = collecttime;
        this.source = source;
        this.counter = counter;
        this.good = good;
        this.comments = comments;
        this.hometext = hometext;
        this.bodytext = bodytext;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    @NotNull
    public String getPubtime() {
        return pubtime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPubtime(@NotNull String pubtime) {
        this.pubtime = pubtime;
    }

    @NotNull
    public String getCollecttime() {
        return collecttime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCollecttime(@NotNull String collecttime) {
        this.collecttime = collecttime;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @NotNull
    public String getCounter() {
        return counter;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCounter(@NotNull String counter) {
        this.counter = counter;
    }

    public String getGood() {
        return good;
    }

    public void setGood(String good) {
        this.good = good;
    }

    @NotNull
    public String getComments() {
        return comments;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComments(@NotNull String comments) {
        this.comments = comments;
    }

    public String getHometext() {
        return hometext;
    }

    public void setHometext(String hometext) {
        this.hometext = hometext;
    }

    public String getBodytext() {
        return bodytext;
    }

    public void setBodytext(String bodytext) {
        this.bodytext = bodytext;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
