package app.taolin.cnbeta.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HEADLINE".
*/
public class HeadlineDao extends AbstractDao<Headline, String> {

    public static final String TABLENAME = "HEADLINE";

    /**
     * Properties of entity Headline.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Sid = new Property(0, String.class, "sid", true, "SID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Thumb = new Property(2, String.class, "thumb", false, "THUMB");
        public final static Property Index = new Property(3, int.class, "index", false, "INDEX");
    };


    public HeadlineDao(DaoConfig config) {
        super(config);
    }
    
    public HeadlineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HEADLINE\" (" + //
                "\"SID\" TEXT PRIMARY KEY NOT NULL ," + // 0: sid
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"THUMB\" TEXT NOT NULL ," + // 2: thumb
                "\"INDEX\" INTEGER NOT NULL );"); // 3: index
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HEADLINE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Headline entity) {
        stmt.clearBindings();
 
        String sid = entity.getSid();
        if (sid != null) {
            stmt.bindString(1, sid);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getThumb());
        stmt.bindLong(4, entity.getIndex());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Headline entity) {
        stmt.clearBindings();
 
        String sid = entity.getSid();
        if (sid != null) {
            stmt.bindString(1, sid);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getThumb());
        stmt.bindLong(4, entity.getIndex());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Headline readEntity(Cursor cursor, int offset) {
        Headline entity = new Headline( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // sid
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2), // thumb
            cursor.getInt(offset + 3) // index
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Headline entity, int offset) {
        entity.setSid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setThumb(cursor.getString(offset + 2));
        entity.setIndex(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Headline entity, long rowId) {
        return entity.getSid();
    }
    
    @Override
    public String getKey(Headline entity) {
        if(entity != null) {
            return entity.getSid();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
