package app.taolin.cnbeta.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HEADLINE".
 */
@Entity
public class Headline {

    @Id
    private String sid;

    @NotNull
    private String title;

    @NotNull
    private String thumb;
    private int index;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Headline() {
    }

    public Headline(String sid) {
        this.sid = sid;
    }

    @Generated
    public Headline(String sid, String title, String thumb, int index) {
        this.sid = sid;
        this.title = title;
        this.thumb = thumb;
        this.index = index;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    @NotNull
    public String getThumb() {
        return thumb;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setThumb(@NotNull String thumb) {
        this.thumb = thumb;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
