package app.taolin.cnbeta.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LIST_ITEM".
 */
@Entity
public class ListItem implements Comparable<ListItem> {

    @Id
    private String sid;

    @NotNull
    private String title;
    private String pubtime;
    private boolean isread;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ListItem() {
    }

    public ListItem(String sid) {
        this.sid = sid;
    }

    @Generated
    public ListItem(String sid, String title, String pubtime, boolean isread) {
        this.sid = sid;
        this.title = title;
        this.pubtime = pubtime;
        this.isread = isread;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    public String getPubtime() {
        return pubtime;
    }

    public void setPubtime(String pubtime) {
        this.pubtime = pubtime;
    }

    public boolean getIsread() {
        return isread;
    }

    public void setIsread(boolean isread) {
        this.isread = isread;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int compareTo(ListItem another) {
        return another.pubtime.compareTo(pubtime);
    }
    // KEEP METHODS END

}
