package app.taolin.cnbeta.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LIST_ITEM".
*/
public class ListItemDao extends AbstractDao<ListItem, String> {

    public static final String TABLENAME = "LIST_ITEM";

    /**
     * Properties of entity ListItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Sid = new Property(0, String.class, "sid", true, "SID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Pubtime = new Property(2, String.class, "pubtime", false, "PUBTIME");
        public final static Property Isread = new Property(3, boolean.class, "isread", false, "ISREAD");
        public final static Property Isfavor = new Property(4, boolean.class, "isfavor", false, "ISFAVOR");
        public final static Property Isheadline = new Property(5, boolean.class, "isheadline", false, "ISHEADLINE");
        public final static Property Collecttime = new Property(6, String.class, "collecttime", false, "COLLECTTIME");
        public final static Property Thumb = new Property(7, String.class, "thumb", false, "THUMB");
        public final static Property Headindex = new Property(8, Integer.class, "headindex", false, "HEADINDEX");
    };


    public ListItemDao(DaoConfig config) {
        super(config);
    }
    
    public ListItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIST_ITEM\" (" + //
                "\"SID\" TEXT PRIMARY KEY NOT NULL ," + // 0: sid
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"PUBTIME\" TEXT NOT NULL ," + // 2: pubtime
                "\"ISREAD\" INTEGER NOT NULL ," + // 3: isread
                "\"ISFAVOR\" INTEGER NOT NULL ," + // 4: isfavor
                "\"ISHEADLINE\" INTEGER NOT NULL ," + // 5: isheadline
                "\"COLLECTTIME\" TEXT," + // 6: collecttime
                "\"THUMB\" TEXT," + // 7: thumb
                "\"HEADINDEX\" INTEGER);"); // 8: headindex
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIST_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ListItem entity) {
        stmt.clearBindings();
 
        String sid = entity.getSid();
        if (sid != null) {
            stmt.bindString(1, sid);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getPubtime());
        stmt.bindLong(4, entity.getIsread() ? 1L: 0L);
        stmt.bindLong(5, entity.getIsfavor() ? 1L: 0L);
        stmt.bindLong(6, entity.getIsheadline() ? 1L: 0L);
 
        String collecttime = entity.getCollecttime();
        if (collecttime != null) {
            stmt.bindString(7, collecttime);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(8, thumb);
        }
 
        Integer headindex = entity.getHeadindex();
        if (headindex != null) {
            stmt.bindLong(9, headindex);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ListItem entity) {
        stmt.clearBindings();
 
        String sid = entity.getSid();
        if (sid != null) {
            stmt.bindString(1, sid);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getPubtime());
        stmt.bindLong(4, entity.getIsread() ? 1L: 0L);
        stmt.bindLong(5, entity.getIsfavor() ? 1L: 0L);
        stmt.bindLong(6, entity.getIsheadline() ? 1L: 0L);
 
        String collecttime = entity.getCollecttime();
        if (collecttime != null) {
            stmt.bindString(7, collecttime);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(8, thumb);
        }
 
        Integer headindex = entity.getHeadindex();
        if (headindex != null) {
            stmt.bindLong(9, headindex);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ListItem readEntity(Cursor cursor, int offset) {
        ListItem entity = new ListItem( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // sid
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2), // pubtime
            cursor.getShort(offset + 3) != 0, // isread
            cursor.getShort(offset + 4) != 0, // isfavor
            cursor.getShort(offset + 5) != 0, // isheadline
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // collecttime
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // thumb
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // headindex
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ListItem entity, int offset) {
        entity.setSid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setPubtime(cursor.getString(offset + 2));
        entity.setIsread(cursor.getShort(offset + 3) != 0);
        entity.setIsfavor(cursor.getShort(offset + 4) != 0);
        entity.setIsheadline(cursor.getShort(offset + 5) != 0);
        entity.setCollecttime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setThumb(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHeadindex(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(ListItem entity, long rowId) {
        return entity.getSid();
    }
    
    @Override
    public String getKey(ListItem entity) {
        if(entity != null) {
            return entity.getSid();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
