package app.taolin.cnbeta.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LIST_ITEM".
 */
@Entity
public class ListItem implements Comparable<ListItem> {

    @Id
    private String sid;

    @NotNull
    private String title;

    @NotNull
    private String pubtime;
    private boolean isread;
    private boolean isfavor;
    private boolean isheadline;
    private String collecttime;
    private String thumb;
    private Integer headindex;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ListItem() {
    }

    public ListItem(String sid) {
        this.sid = sid;
    }

    @Generated
    public ListItem(String sid, String title, String pubtime, boolean isread, boolean isfavor, boolean isheadline, String collecttime, String thumb, Integer headindex) {
        this.sid = sid;
        this.title = title;
        this.pubtime = pubtime;
        this.isread = isread;
        this.isfavor = isfavor;
        this.isheadline = isheadline;
        this.collecttime = collecttime;
        this.thumb = thumb;
        this.headindex = headindex;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    @NotNull
    public String getPubtime() {
        return pubtime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPubtime(@NotNull String pubtime) {
        this.pubtime = pubtime;
    }

    public boolean getIsread() {
        return isread;
    }

    public void setIsread(boolean isread) {
        this.isread = isread;
    }

    public boolean getIsfavor() {
        return isfavor;
    }

    public void setIsfavor(boolean isfavor) {
        this.isfavor = isfavor;
    }

    public boolean getIsheadline() {
        return isheadline;
    }

    public void setIsheadline(boolean isheadline) {
        this.isheadline = isheadline;
    }

    public String getCollecttime() {
        return collecttime;
    }

    public void setCollecttime(String collecttime) {
        this.collecttime = collecttime;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public Integer getHeadindex() {
        return headindex;
    }

    public void setHeadindex(Integer headindex) {
        this.headindex = headindex;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int compareTo(ListItem another) {
        if (another.isfavor && isfavor) {
            return another.collecttime.compareTo(collecttime);
        }
        return another.pubtime.compareTo(pubtime);
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof ListItem) {
            ListItem h = (ListItem) o;
            return sid.equals(h.sid);
        }
        return false;
    }

    // KEEP METHODS END

}
